### ISSUE TITLE
Guys is there something similar to this, you guys working on 

### ISSUE THREAD

**Issue by murarisumit** [bitprophet/botox#1]
Hi guys, was looking for something like this. 
Do you guys know similar project that you guys are working on and any plans to work on it ?

**Comment by bitprophet** [comment]
Nope, this is dead, sorry! I'll update it to be archived or whatever feature GH added recently.

I'm sure other "above Boto" libs exist, but boto3 also came out after this did and has a marginally nicer interface than boto(1), too.
